version: '3.1'
services:
  api:
    build: .
    environment:
      - NODE_ENV
    container_name: api
    volumes:
      - api-data:/data
    ports:
      - '3333:3333'
    networks:
      - api-network
    depends_on:
      - postgres
      - mongodb
      - redis
  postgres:
    container_name: api-postgres
    image: bitnami/postgresql:latest
    volumes:
      - api-postgres-data:/data
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASS}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - api-network
  redis:
    image: bitnami/redis:latest
    container_name: api-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - api-redis-data:/data
    networks:
      - api-network

volumes:
  api-data:
  api-postgres-data:
  api-redis-data:

networks:
  api-network:
    driver: bridge
