version: '3.1'
services:
  postgres:
    container_name: api-postgres
    image: bitnami/postgresql:latest
    volumes:
      - api-postgres-data:/data
    environment:
      - TZ='America/Sao_Paulo'
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASS}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    ports:
      - '5432:5432'
  redis:
    image: bitnami/redis:latest
    container_name: api-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - api-redis-data:/data
    ports:
      - '6379:6379'

volumes:
  api-postgres-data:
  api-redis-data:
